# Generated by Django 5.2.5 on 2025-08-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
