# Generated by Django 5.2.5 on 2025-08-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tutorprofile_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrequest',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
