# Generated by Django 5.2.5 on 2025-08-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lessonrequest_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='duration_minutes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterModelTable(
            name='lessonrequest',
            table='lesson_requests',
        ),
    ]
